name: Run test suite

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Start containers
      run: docker compose -f "docker-compose-test.yaml" up -d --build
    - name: Run django entrypoint
      run: docker exec django4importer /bin/sh -c "sh /usr/src/importer/entrypoint_test.sh"
    - name: Run geonode-importer tests
      run: docker exec django4importer /bin/sh -c "sh /usr/src/importer/runtest.sh"
    - name: Coverage comment
      id: coverage_comment
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Store Pull Request comment to be posted
      uses: actions/upload-artifact@v4
      if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
      with:
        name: python-coverage-comment-action
        path: python-coverage-comment-action.txt
    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose-test.yaml" down