name: Run test suite

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: adambirds/docker-compose-action@v1.3.0
      with:
        compose-file: "docker-compose-test.yaml"
        down-flags: "--volumes"
        test-container: django4importer
        test-command: "sh /usr/src/importer/entrypoint_test.sh"